# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Just thoughts
email: pravin.chaudhary.me@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here I rant
url: "http://pravinkc.github.io" # the base hostname & protocol for your site
github_username:  pravinkc

# Build settings
markdown: kramdown
